import type { Metadata } from "next";
// 修正 1: 从 'geist' 包中导入字体，而不是 'next/font/google'
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

// 你原来的 Pacifico 字体可以保留，因为它确实是 Google Font
import { Pacifico } from "next/font/google";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* 修正 2: 使用 GeistSans.variable 和 GeistMono.variable */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}